/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchetypesRouteImport } from './routes/archetypes'
import { Route as ModelFeaturesRouteImport } from './routes/model-features'
import { Route as StatsRouteImport } from './routes/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesRoute = ArchetypesRouteImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelFeaturesRoute = ModelFeaturesRouteImport.update({
  id: '/model-features',
  path: '/model-features',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/model-features': typeof ModelFeaturesRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/model-features': typeof ModelFeaturesRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/model-features': typeof ModelFeaturesRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archetypes' | '/model-features' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archetypes' | '/model-features' | '/stats'
  id: '__root__' | '/' | '/archetypes' | '/model-features' | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypesRoute: typeof ArchetypesRoute
  ModelFeaturesRoute: typeof ModelFeaturesRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes': {
      id: '/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof ArchetypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-features': {
      id: '/model-features'
      path: '/model-features'
      fullPath: '/model-features'
      preLoaderRoute: typeof ModelFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypesRoute: ArchetypesRoute,
  ModelFeaturesRoute: ModelFeaturesRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
